name: taskzilla
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.1
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/img/zilla.png

  fonts:
    - family: LondrinaSolid
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
          weight: 400
        - asset: assets/fonts/LondrinaSolid-Black.ttf
          weight: 900
        - asset: assets/fonts/LondrinaSolid-Light.ttf
          weight: 300
        - asset: assets/fonts/LondrinaSolid-Thin.ttf
          weight: 100

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400

  uses-material-design: true
